import '../globals.css'
import Head from "../head"
import Header from "../header"
import { Inter } from 'next/font/google'

import { SocketContextProvider } from "@/app/_context/socket"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head />
      <body id="app" className={inter.className}>
        {/* <Header /> */}
        <SocketContextProvider>
          {children}
        </SocketContextProvider>
      </body>
    </html>
  )
}
